public class PostOfficeBranch
{
    public string Name{set;get;}
    public string Description{set;get;}
    public string BranchType{set;get;}
    public string DeliveryStatus{set;get;}
    public string Circle{set;get;}
    public string District{set;get;}
    public string Divison{set;get;}
    public string Region{set;get;}
    public string State{set;get;}
     public string Country{set;get;}
    

}