public with sharing class PostOffice {


		public String name {set;get;}
		public Object description {set;get;}
		public String branchType {set;get;}
		public String deliveryStatus {set;get;}
		public String circle {set;get;}
		public String district {set;get;}
		public String division {set;get;}
		public String region {set;get;}
		public String block {set;get;}
		public String state {set;get;}
		public String country {set;get;}
		public String pincode {set;get;}
	}

